### Python 기초

In [11]:
# int
a = 3
b = 5
print(a + b)

8


In [12]:
# float
a = 3.5
b = 2.5
print(a - b)

1.0


In [13]:
# string
a = "hi"
b = 'hi'
print(a)
print(b)

hi
hi


In [14]:
# 리스트 (List) 사용법
a = [1, 2, 3, 4, 5]
print(a, len(a))

b = ["a", "b", "c", "d"]
print(b, len(b))

c = [1, "a", 2.5]
print(c, len(c))

[1, 2, 3, 4, 5] 5
['a', 'b', 'c', 'd'] 4
[1, 'a', 2.5] 3


In [15]:
# dictionary 사용법
name_to_age = {
    "Jenny": 20
}
name_to_age["John"] = 26
name_to_age["Tom"] = 29

In [16]:
print(name_to_age["Jenny"])
print(name_to_age["John"])
print(name_to_age["Tom"])

20
26
29


In [17]:
name_to_age["Jenny"] = 21
print(name_to_age["Jenny"])

21


In [18]:
# function 사용법
def sum(a, b):
    return a + b


print(sum(3, 5))
print(sum(2, 1))


8
3


In [19]:
def sum_and_mul(a, b):
    return a + b, a*b

print(sum_and_mul(3, 5))
print(sum_and_mul(2, 1))


(8, 15)
(3, 2)


In [2]:
def is_adult(age):
    if age >= 20:
        return True
    else:
        return False

In [3]:
is_adult(20)

True

In [4]:
is_adult(5)

False

In [5]:
def get_average(score_list):
    total = 0
    for score in score_list:
        total += score
    average = total/len(score_list)
    return average

In [7]:
score_list = [100, 90, 80, 95, 85]

In [8]:
print(get_average(score_list))

90.0


In [12]:
def get_average(score_list):
    total = 0
    for i in range(len(score_list)):
        total += score_list[i]
    average = total/len(score_list)
    return average

In [13]:
score_list = [100, 90, 80, 95, 85]

In [14]:
print(get_average(score_list))

90.0


In [19]:
def get_average(score_list):
    total = 0
    i = 0
    while i < len(score_list):
        total += score_list[i]
        i += 1
    average = total/len(score_list)
    return average

In [20]:
score_list = [100, 90, 80, 95, 85]

In [21]:
print(get_average(score_list))

90.0


In [20]:
import numpy

In [21]:
list_matrix = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]
matrix = numpy.array(list_matrix)

print(matrix)
print(matrix.shape)

[[1 2 3]
 [3 6 9]
 [2 4 6]]
(3, 3)


In [23]:
print(matrix[1, 2])

9


In [24]:
print(matrix[1])

[3 6 9]


In [25]:
print(matrix[1: 3])

[[3 6 9]
 [2 4 6]]


In [26]:
print(matrix[:, 1])

[2 6 4]


In [27]:
print(matrix)
matrix = matrix + 3
print(matrix)

[[1 2 3]
 [3 6 9]
 [2 4 6]]
[[ 4  5  6]
 [ 6  9 12]
 [ 5  7  9]]


In [28]:
matrix = matrix + matrix
print(matrix)

[[ 8 10 12]
 [12 18 24]
 [10 14 18]]


In [30]:
for i in range(3):
    matrix = numpy.random.rand(3, 3)
    print("%d번째 랜덤 matrix" % (i))
    print(matrix)

0번째 랜덤 matrix
[[ 0.34149236  0.46770167  0.59394967]
 [ 0.1931466   0.3458594   0.01643549]
 [ 0.69890863  0.01290042  0.70755391]]
1번째 랜덤 matrix
[[ 0.20347051  0.96590231  0.96894159]
 [ 0.79523847  0.29297558  0.46727225]
 [ 0.2977582   0.79355549  0.80635825]]
2번째 랜덤 matrix
[[ 0.58251489  0.1296004   0.08914049]
 [ 0.55012782  0.48289467  0.45836755]
 [ 0.78697852  0.07547408  0.93740577]]


In [32]:
matrix = numpy.zeros((3, 3))
print(matrix)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [33]:
list_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix1 = numpy.array(list_matrix)

matrix2 = numpy.array([1, 2, 3])

In [34]:
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(matrix2)

[1 2 3]


In [36]:
print(matrix1*matrix2)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [37]:
print(numpy.dot(matrix1, matrix2))

[14 32 50]
